version: '3'

services:

  #PostgreSQL
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=currconv
      - POSTGRES_USER=kambu
      - POSTGRES_PASSWORD=kambu123@


  #Spring Boot
  currency-app:
    build:
      context: .
    depends_on:
      - db
    environment:
      - spring.profiles.active=prod
    ports:
      - "8080"
    links:
      - db

  #Angular
  currency-frontend:
    build: ./frontend
    container_name: currency-frontend
    ports:
      - 4200:80
    links:
      - currency-app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - currency-app
    ports:
      - 8080:8080
