# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

services:

  #PostgreSQL
  currency-postgres:
    image: 'postgres:13.1-alpine'
    container_name: currency-postgres
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=currconv
      - POSTGRES_USER=kambu
      - POSTGRES_PASSWORD=kambu123@


  #Spring Boot
  currency-app:
#    build: ./Dockerfile
    build:
      context: .
    container_name: currency-app
    depends_on:
      - currency-postgres

    environment:
      - DB_SERVER=currency-postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://currency-postgres:5432/currconv
      - POSTGRES_DB=currconv
      - POSTGRES_USER=kambu
      - POSTGRES_PASSWORD=kambu123@
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - 8080:8080
    links:
      - currency-postgres

  #Angular
  currency-frontend:
    build: ./frontend
    container_name: currency-frontend
    ports:
      - 4200:80
    links:
      - currency-app

