-- insert into currency (code)
-- values ('GBP');
-- insert into currency (code)
-- values ('EUR');
-- insert into currency (code)
-- values ('USD');
-- insert into currency (code)
-- values ('AUD');
-- insert into currency (code)
-- values ('JPY');
-- insert into currency (code)
-- values ('ISK');
-- insert into currency (code)
-- values ('HUF');
-- insert into currency (code)
-- values ('PLN');
